### ISSUE TITLE
Add information to the wiki

### ISSUE THREAD

**Issue by willyb321** [willyb321/SDD-GameShow-Wiki#2]
The pages from #1 need to have information added to them. I can add info to the first 2, and @BENNEW99 can do the other 2 pages. Making sure to credit sources and whatnot.

**Comment by willyb321** [comment]
Read the sheet again and realised that i was doing it wrong, but [this](https://github.com/willyb321/SDD-GameShow-Wiki/wiki/The-5-Generations) page has the **5** generations of programming languages, and needs to have information added to it. I have done 1 of the 5 already.

**Comment by willyb321** [comment]
added some more information

**Comment by willyb321** [comment]
@Slothe69 (tagging so you get notifications)

**Comment by willyb321** [comment]
Done. Check revisions on wiki pages for contributors.

**Comment by Slothe69** [comment]
Is there anything you need me to do for the wiki or gameshow

Date: Sun, 27 Mar 2016 19:56:02 -0700

**Comment by willyb321** [comment]
@Slothe69 nope, its pretty much all done. You can probably help Ben do the presenting. I'm thinking we get the quiz up on the computers and get people to do it. That or put the quiz on the projector, and people can look at the wiki to get answers or something
